from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any


class ErrorCode(StrEnum):
    BUNDLE_NOT_FOUND = "BUNDLE_NOT_FOUND"
    BUNDLE_YAML_ERROR = "BUNDLE_YAML_ERROR"
    BUNDLE_DUPLICATE_KEY = "BUNDLE_DUPLICATE_KEY"
    BUNDLE_SCHEMA_ERROR = "BUNDLE_SCHEMA_ERROR"
    BUNDLE_PATH_ERROR = "BUNDLE_PATH_ERROR"
    BUNDLE_SPECIAL_FILE_ERROR = "BUNDLE_SPECIAL_FILE_ERROR"
    BUNDLE_DIGEST_ERROR = "BUNDLE_DIGEST_ERROR"
    SNAPSHOT_WRITE_ERROR = "SNAPSHOT_WRITE_ERROR"
    SNAPSHOT_READ_ERROR = "SNAPSHOT_READ_ERROR"
    SNAPSHOT_SCHEMA_ERROR = "SNAPSHOT_SCHEMA_ERROR"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    GIT_NOT_AVAILABLE = "GIT_NOT_AVAILABLE"
    GIT_VERSION_ERROR = "GIT_VERSION_ERROR"
    SOURCE_URL_ERROR = "SOURCE_URL_ERROR"
    SOURCE_COMMIT_FORMAT_ERROR = "SOURCE_COMMIT_FORMAT_ERROR"
    SOURCE_FETCH_ERROR = "SOURCE_FETCH_ERROR"
    SOURCE_OBJECT_ERROR = "SOURCE_OBJECT_ERROR"
    SOURCE_COMMIT_MISMATCH = "SOURCE_COMMIT_MISMATCH"
    SOURCE_TREE_ERROR = "SOURCE_TREE_ERROR"
    SOURCE_TREE_UNSAFE = "SOURCE_TREE_UNSAFE"
    SOURCE_SUBMODULE_UNSUPPORTED = "SOURCE_SUBMODULE_UNSUPPORTED"
    SOURCE_MATERIALIZATION_ERROR = "SOURCE_MATERIALIZATION_ERROR"
    SOURCE_SYMLINK_UNSAFE = "SOURCE_SYMLINK_UNSAFE"
    SOURCE_MANIFEST_ERROR = "SOURCE_MANIFEST_ERROR"
    SOURCE_PERSISTENCE_ERROR = "SOURCE_PERSISTENCE_ERROR"
    SOURCE_CLEANUP_ERROR = "SOURCE_CLEANUP_ERROR"
    DOCKER_NOT_AVAILABLE = "DOCKER_NOT_AVAILABLE"
    DOCKER_VERSION_ERROR = "DOCKER_VERSION_ERROR"
    DOCKER_DAEMON_ERROR = "DOCKER_DAEMON_ERROR"
    DOCKER_REMOTE_UNSUPPORTED = "DOCKER_REMOTE_UNSUPPORTED"
    BUILD_CONFIG_ERROR = "BUILD_CONFIG_ERROR"
    BUILD_CONTEXT_ERROR = "BUILD_CONTEXT_ERROR"
    BUILD_TIMEOUT = "BUILD_TIMEOUT"
    IMAGE_BUILD_ERROR = "IMAGE_BUILD_ERROR"
    IMAGE_INSPECT_ERROR = "IMAGE_INSPECT_ERROR"
    IMAGE_IDENTITY_ERROR = "IMAGE_IDENTITY_ERROR"
    PLATFORM_MISMATCH = "PLATFORM_MISMATCH"
    SMOKE_TIMEOUT = "SMOKE_TIMEOUT"
    LOCK_READ_ERROR = "LOCK_READ_ERROR"
    LOCK_WRITE_ERROR = "LOCK_WRITE_ERROR"
    ARTIFACT_WRITE_ERROR = "ARTIFACT_WRITE_ERROR"
    REPORT_WRITE_ERROR = "REPORT_WRITE_ERROR"
    CONFIG_ERROR = "CONFIG_ERROR"
    SOURCE_ERROR = "SOURCE_ERROR"
    BUILD_ERROR = "BUILD_ERROR"
    IMAGE_ERROR = "IMAGE_ERROR"
    SMOKE_CHECK_ERROR = "SMOKE_CHECK_ERROR"
    LOCK_MISMATCH = "LOCK_MISMATCH"
    VALIDATION_LOCK_REQUIRED = "VALIDATION_LOCK_REQUIRED"
    VALIDATION_LOCK_STALE = "VALIDATION_LOCK_STALE"
    VALIDATION_IMAGE_MISSING = "VALIDATION_IMAGE_MISSING"
    EVALUATOR_CREATE_ERROR = "EVALUATOR_CREATE_ERROR"
    EVALUATOR_STAGE_ERROR = "EVALUATOR_STAGE_ERROR"
    EVALUATOR_PERMISSION_ERROR = "EVALUATOR_PERMISSION_ERROR"
    WORKSPACE_SEED_ERROR = "WORKSPACE_SEED_ERROR"
    TEST_PATCH_APPLY_ERROR = "TEST_PATCH_APPLY_ERROR"
    GOLDEN_PATCH_APPLY_ERROR = "GOLDEN_PATCH_APPLY_ERROR"
    TEST_PREPARE_TIMEOUT = "TEST_PREPARE_TIMEOUT"
    TEST_RUNNER_TIMEOUT = "TEST_RUNNER_TIMEOUT"
    TEST_RESULT_MISSING = "TEST_RESULT_MISSING"
    TEST_RESULT_TOO_LARGE = "TEST_RESULT_TOO_LARGE"
    TEST_RESULT_SCHEMA_ERROR = "TEST_RESULT_SCHEMA_ERROR"
    INVALID_BASELINE = "INVALID_BASELINE"
    INVALID_BASELINE_FLAKY = "INVALID_BASELINE_FLAKY"
    INVALID_GOLDEN = "INVALID_GOLDEN"
    INVALID_GOLDEN_FLAKY = "INVALID_GOLDEN_FLAKY"
    VALIDATION_CLEANUP_ERROR = "VALIDATION_CLEANUP_ERROR"
    VALIDATION_REQUIRED = "VALIDATION_REQUIRED"
    SOLVER_CONTEXT_ERROR = "SOLVER_CONTEXT_ERROR"
    PATCH_EXTRACTION_ERROR = "PATCH_EXTRACTION_ERROR"
    PATCH_APPLY_ERROR = "PATCH_APPLY_ERROR"
    PATCH_POLICY_ERROR = "PATCH_POLICY_ERROR"
    PATCH_CONFLICT = "PATCH_CONFLICT"
    TEST_PREPARE_ERROR = "TEST_PREPARE_ERROR"
    TEST_RUNNER_ERROR = "TEST_RUNNER_ERROR"
    TEST_PARSE_ERROR = "TEST_PARSE_ERROR"
    TEST_RESULT_INCOMPLETE = "TEST_RESULT_INCOMPLETE"
    BASELINE_GUARDRAIL_ERROR = "BASELINE_GUARDRAIL_ERROR"
    GOLDEN_VALIDATION_ERROR = "GOLDEN_VALIDATION_ERROR"
    SOLVER_ERROR = "SOLVER_ERROR"
    SOLVER_TIMEOUT = "SOLVER_TIMEOUT"
    SOLVER_OUTPUT_ERROR = "SOLVER_OUTPUT_ERROR"
    CONTAINER_ERROR = "CONTAINER_ERROR"
    TIMEOUT = "TIMEOUT"
    DATABASE_ERROR = "DATABASE_ERROR"
    CLEANUP_ERROR = "CLEANUP_ERROR"


@dataclass(frozen=True, slots=True)
class ErrorContext:
    phase: str
    expected: str
    actual: str
    corrective_action: str
    selector: str | None = None
    path: Path | None = None
    artifact: Path | None = None
    details: dict[str, Any] | None = None


class TaskBundleError(Exception):
    def __init__(self, code: ErrorCode, message: str, context: ErrorContext) -> None:
        super().__init__(message)
        self.code = code
        self.context = context

    @property
    def exit_code(self) -> int:
        return exit_code_for_error(self.code)


_CONFIG_CODES = {
    ErrorCode.BUNDLE_NOT_FOUND,
    ErrorCode.BUNDLE_YAML_ERROR,
    ErrorCode.BUNDLE_DUPLICATE_KEY,
    ErrorCode.BUNDLE_SCHEMA_ERROR,
    ErrorCode.BUNDLE_PATH_ERROR,
    ErrorCode.BUNDLE_SPECIAL_FILE_ERROR,
    ErrorCode.SNAPSHOT_READ_ERROR,
    ErrorCode.SNAPSHOT_SCHEMA_ERROR,
    ErrorCode.SNAPSHOT_STALE,
    ErrorCode.SOURCE_URL_ERROR,
    ErrorCode.SOURCE_COMMIT_FORMAT_ERROR,
    ErrorCode.BUILD_CONFIG_ERROR,
    ErrorCode.LOCK_READ_ERROR,
    ErrorCode.CONFIG_ERROR,
    ErrorCode.LOCK_MISMATCH,
    ErrorCode.VALIDATION_LOCK_REQUIRED,
    ErrorCode.VALIDATION_LOCK_STALE,
    ErrorCode.VALIDATION_IMAGE_MISSING,
    ErrorCode.VALIDATION_REQUIRED,
}
_VALIDATION_CODES = {
    ErrorCode.BASELINE_GUARDRAIL_ERROR,
    ErrorCode.GOLDEN_VALIDATION_ERROR,
    ErrorCode.TEST_PATCH_APPLY_ERROR,
    ErrorCode.GOLDEN_PATCH_APPLY_ERROR,
    ErrorCode.INVALID_BASELINE,
    ErrorCode.INVALID_BASELINE_FLAKY,
    ErrorCode.INVALID_GOLDEN,
    ErrorCode.INVALID_GOLDEN_FLAKY,
}
_SOLVER_CODES = {
    ErrorCode.SOLVER_CONTEXT_ERROR,
    ErrorCode.SOLVER_ERROR,
    ErrorCode.SOLVER_TIMEOUT,
    ErrorCode.SOLVER_OUTPUT_ERROR,
}
_PATCH_CODES = {
    ErrorCode.PATCH_EXTRACTION_ERROR,
    ErrorCode.PATCH_APPLY_ERROR,
    ErrorCode.PATCH_POLICY_ERROR,
    ErrorCode.PATCH_CONFLICT,
}


def exit_code_for_error(code: ErrorCode) -> int:
    if code in _CONFIG_CODES:
        return 2
    if code in _VALIDATION_CODES:
        return 4
    if code in _SOLVER_CODES:
        return 5
    if code in _PATCH_CODES:
        return 6
    return 3
